obj-m +=create_device.o

all:
	#$(MAKE) -C '/home/nara/Kernel_Hacking/linux-next' M='$(PWD)' modules
	make -C '/home/nara/Kernel_Hacking/linux-next' M='$(PWD)' modules

clean:
	#$(MAKE) -C '/home/nara/Kernel_Hacking/linux-next' M='$(PWD)' clean
	make -C '/home/nara/Kernel_Hacking/linux-next' M='$(PWD)' clean
